### ISSUE TITLE
 No module named 'editdistance' & No module named 'tensorflow'

### ISSUE THREAD

**Issue by angelperezleon** [HarshViijay/HandwritingRecognition-OCR#1]
```console
(cv) pi@rpi4:/opt/HandwritingRecognition-OCR/scripts $ python main.py
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    import editdistance
ModuleNotFoundError: No module named 'editdistance'
(cv) pi@rpi4:/opt/HandwritingRecognition-OCR/scripts $ python Model.py
Traceback (most recent call last):
  File "Model.py", line 6, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'
```

What do i need todo here?

**Comment by HarshViijay** [comment]
Hey,
Try installing editdistance and tensorflow module using:
pip install editdistance
https://www.tensorflow.org/install/pip
